### ISSUE TITLE
Survey for Knowledge Graphs Meet Multi-Modal Learning

### ISSUE THREAD

**Issue by hackerchenzhuo** [ZihengZZH/awesome-multimodal-knowledge-graph#4]
Hi, we have preprinted our Survey recently: **[Knowledge Graphs Meet Multi-Modal Learning: A Comprehensive Survey](http://arxiv.org/abs/2402.05391)  [[`Repo`](https://github.com/zjukg/KG-MM-Survey)].**

Would you mind involving it in your Repo?

Thank you so much!

**Comment by ZihengZZH** [comment]
Sure thing.
